version: '2'
services:
  web:
    build: .
    image: backend:nodejs
    container_name: backend-nodejs
    command: npm start
    volumes:
      - ../nodejs-docker:/backend
    ports:
      - "3000:3000"